run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - tmp
    - bin

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    check-shadowing: true
    enable-all: true
    
  gocyclo:
    min-complexity: 10
    
  maligned:
    suggest-new: true
    
  dupl:
    threshold: 100
    
  goconst:
    min-len: 3
    min-occurrences: 3
    
  misspell:
    locale: US
    
  lll:
    line-length: 120
    
  goimports:
    local-prefixes: go-template-structure
    
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - varcheck
    - structcheck
    - deadcode
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - interfacer
    - unconvert
    - dupl
    - goconst
    - gocognit
    - misspell
    - lll
    - unparam
    - nakedret
    - prealloc
    - scopelint
    - gocritic
  disable:
    - maligned

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - path: cmd/
      linters:
        - gocyclo
    - text: "weak cryptographic primitive"
      linters:
        - gosec
